### ISSUE TITLE
[GHA] Test Scripts workflow for macos is broken

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino-operator#141]
`make operator-sdk` fails when executed by the GitHub action [Test Scripts](https://github.com/Kuadrant/authorino-operator/blob/261466db34fa01c066249931f902f358c323f70d/.github/workflows/test.yaml#L56-L76) for `macos-latest` platform.

E.g. https://github.com/Kuadrant/authorino-operator/actions/runs/6313837883/job/17142801232?pr=140

**Comment by Boomatang** [comment]
I have seen this happen with more that just the `macos-latest`, it also happens on the `ubuntu-latest`. But it is a flaky, I found when the checks are reran they pass the second time. It does seem to be the same error each time.

**Comment by guicassolato** [comment]
Fixed at https://github.com/Kuadrant/authorino-operator/pull/147
