### ISSUE TITLE
Install authorino-operator in Air-gapped environment or helm chart of the Operator

### ISSUE THREAD

**Issue by vchauhan1** [Kuadrant/authorino-operator#149]
Dear Team, 

Do we have a way to install Operator in disconnected kubernetes cluster ? Or maybe there is a helm-chart to install and configure it using ArgoCD.  Please refer to the link or location where I can find the details about it

**Comment by guicassolato** [comment]
@vchauhan1, the 2 recommended ways to install Authorino Operator are by using [OLM](https://github.com/kuadrant/authorino-operator#installing-via-olm) or the [install script](https://github.com/Kuadrant/authorino-operator/blob/main/utils/install.sh) (dev workflow and demos mainly.) These methods are slightly trickier to adapt for disconnected install.

However, provided you have [cert-manager](https://cert-manager.io/) already installed, you can install the operator by applying, for example, this single manifest file: https://raw.githubusercontent.com/Kuadrant/authorino-operator/v0.9.0/config/deploy/manifests.yaml (which is basically what the install script does.)

You can create a copy of the file and tweak with it a little bit. In the `authorino-operator` and `authorino-webhooks` deployments, modify the images with ones you push in advance to your registry and maybe set `imagePullPolicy: IfNotPresent`.

The `Authorino` CR also allows setting `image` and `imagePullPolicy` to override the defaults. This may require some additional watching for potential version mismatch between operator and operand and therefore caution when rolling out upgrades.

**Comment by vchauhan1** [comment]
@guicassolato , Thanks for the response. This is amazing and it worked.  If we can have Helm chart for Operator to get it installed in disconnected envs would be great.

**Comment by KevFan** [comment]
We now have a helm chart for installinf Authorino Operator https://artifacthub.io/packages/helm/kuadrant/authorino-operator

@guicassolato Do you think we can close this issue?
