### ISSUE TITLE
SHA builds do not use fixed Authorino image

### ISSUE THREAD

**Issue by pehala** [Kuadrant/authorino-operator#168]
Currently, the SHA version of authorino-operator uses `quay.io/kuadrant/authorino:latest` for Authorino instances by default. The correct behaviour would be to use a fixed tag, similar to how `limitador-operator` does this.

Workaround exists since it can be overridden in the CR, however, in context of Kuadrant nightly builds it makes it that the build is not complete as not all components use fixed tags. Probably could be solved as part of some greater CI/CD work.

**Comment by guicassolato** [comment]
Confirmed. Maybe Limitador Operator's approach of reading the org var that stores the [most recent SHA of the operand](https://github.com/Kuadrant/limitador-operator/blob/248c5c9281d63ef30e9bf2deab07eddfa092dbea/.github/workflows/build-images-scheduled.yaml#L15) can be of inspiration for the fix.
