### ISSUE TITLE
[question] What is the purpose of cert-manager ?

### ISSUE THREAD

**Issue by eshepelyuk** [Kuadrant/authorino-operator#203]
Hello

The installation script installs cert-manager into the cluster. 
What is the purpose of this component, can it be removed, for local development, for example ?

If it is only to have self signed certificate for webhook , then it can be replaced with pre-defined secret.

**Comment by guicassolato** [comment]
Hi @eshepelyuk.

The purpose of cert-manager is in fact to request a cert for the webhook service.

You can specify `--no-deps` when running the installation script, but it will still create cert-manager `Certificate` and `Issuer` resources.

If you want to install without depending on cert-manager at all, I recommend either relying on [OLM](https://github.com/Kuadrant/authorino-operator?tab=readme-ov-file#installing-via-olm) or creating your own version of the [manifests](https://raw.githubusercontent.com/Kuadrant/authorino-operator/main/config/deploy/manifests.yaml). Hopefully soon the helm chart will let us customize that.

**Comment by eshepelyuk** [comment]
> Hi @eshepelyuk.
> 
> The purpose of cert-manager is in fact to request a cert for the webhook service.
> 
> You can specify `--no-deps` when running the installation script, but it will still create cert-manager `Certificate` and `Issuer` resources.
> 
> If you want to install without depending on cert-manager at all, I recommend either relying on [OLM](https://github.com/Kuadrant/authorino-operator?tab=readme-ov-file#installing-via-olm) or creating your own version of the [manifests](https://raw.githubusercontent.com/Kuadrant/authorino-operator/main/config/deploy/manifests.yaml). Hopefully soon the helm chart will let us customize that.

Thanks for reply, I'll try with custom manifests to assess the project.

**Comment by eshepelyuk** [comment]
@jasonmadigan for example self signed certificates can be generated directly from Helm chart, allowing to completely avoid cert-manager installation.

https://medium.com/nuvo-group-tech/move-your-certs-to-helm-4f5f61338aca
