### ISSUE TITLE
Does not reconcile log level changes

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/authorino-operator#28]
### Steps to reproduce
* Create Authorino CR with no log level spec
* Update CR adding `spec.logLevel = 'debug'`

Authorino is not rolled out with the new conf.

**Comment by jjaferson** [comment]
`logLevel` and `logMode` are added as env variables to the deployment resource of Authorino and if they are not added when the CR is created, the operator is not detecting the change in the deployment as the env vars don't exist in the deployment, therefore the update will not work. 

A quick fix to this is to patch the authorino CR to add the desired env variable. 
```bash
kubectl set env deployment/<authorino-cr-name> LOG_LEVEL=debug  -n <authorino-cr-namespace>
```

I will create a PR to fix this issue and link here.
